### ISSUE TITLE
Equation error in Century model to split STR and MET from litter input

### ISSUE THREAD

**Issue by SongchaoChen** [MPIBGC-TEE/SoilR-exp#1] opened 2020-12-09 14:19 UTC
If I understand correctly, Fm=0.85-0.18*LN should be corrected as Fm=0.85-0.018*LN. Please have a careful check.
Thanks again for your great work.
Cheers,
Songchao

**Comment by crlsierra** [comment] 2020-12-09 22:36
Thanks for pointing this out. 
The problem is now fixed. 

Best,
Carlos

**Closed as completed by crlsierra** 2020-12-09 22:36 UTC
